### ISSUE TITLE
Modernise Hangman.

### ISSUE THREAD

**Issue by Animesh-Ghosh** [InfernoCoder11/Hangman#3]
It would be nice to modularise the functions into a separate header file and implementation files.

May I ask which compiler you are using?

**Comment by adarshme** [comment]
I'm using MinGW-w64 compiler.

**Comment by Animesh-Ghosh** [comment]
> I'm using MinGW-w64 compiler.

OK, I'm using the same.

**Comment by Animesh-Ghosh** [comment]
#4 is merged, closing this issue.
